import FullScreenLoader from '@/components/common/FullScreenLoader';
import { PageContainer } from '@/components/layout/PageContainer';
import { PageHeader } from '@/components/layout/PageHeader';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { useGenerateReflectionInsight } from '@/features/insights/hooks/useGenerateReflectionInsight';
import { useReflectionInsight } from '@/features/insights/hooks/useReflectionInsight';
import SourceReflectionSection from '@/features/reflections/components/SourceReflectionSection';
import { useReflectionById } from '@/features/reflections/hooks/useReflectionById';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { CircleHelp, Compass, Heart, Layers3, Lightbulb, Sparkles } from 'lucide-react';
import InsightSection from '@/components/insights/InsightSection';
import InsightBulletList from '@/components/insights/InsightBulletList';
import InsightShell from '@/components/insights/InsightShell';
import InsightIntro from '@/components/insights/InsightIntro';
import SectionTitle from '@/components/common/SectionTitle';
import { devComponentAttrs } from '@/lib/devtools';
import ReflectionInsightActionsMenu from '@/features/reflections/components/ReflectionInsightActionMenu';
import InsightThemeList from '@/features/insights/components/InsightThemeList';

type ReflectionInsightLocationState = {
  autoGenerateInsight?: boolean;
};

type InsightInfoPopoverProps = {
  label: string;
  children: React.ReactNode;
};

function InsightInfoPopover({ label, children }: InsightInfoPopoverProps) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          className="inline-flex h-7 w-7 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-background/70 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background"
          aria-label={label}
        >
          <CircleHelp className="h-3.5 w-3.5" />
        </button>
      </PopoverTrigger>
      <PopoverContent
        align="start"
        className="max-w-xs border-border/70 bg-popover text-popover-foreground"
      >
        <p className="text-sm leading-6 text-muted-foreground">{children}</p>
      </PopoverContent>
    </Popover>
  );
}

export default function ReflectionInsightPage() {
  const { reflectionId } = useParams<{ reflectionId: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  const autoGenerateInsight =
    (location.state as ReflectionInsightLocationState | null)?.autoGenerateInsight === true;
  const hasAutoGeneratedRef = useRef(false);
  const {
    data: reflection,
    isLoading: isReflectionLoading,
    error: reflectionError,
  } = useReflectionById(reflectionId);
  const {
    data: insight,
    isLoading: isInsightLoading,
    error: insightError,
  } = useReflectionInsight(reflectionId);
  const generateInsightMutation = useGenerateReflectionInsight();
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [isAwaitingGeneratedInsight, setIsAwaitingGeneratedInsight] = useState(false);

  const isLoading = isReflectionLoading || isInsightLoading;

  const handleGenerateInsight = useCallback(async () => {
    if (!reflection) {
      return;
    }

    setGenerationError(null);
    setIsAwaitingGeneratedInsight(true);

    try {
      await generateInsightMutation.mutateAsync({
        reflectionId: reflection.id,
        reflectionText: reflection.journal_text,
        sleepHours: reflection.sleep_hours,
        energy: reflection.energy,
        mood: reflection.mood,
        stress: reflection.stress,
        exercised: reflection.exercised,
      });
    } catch (error) {
      setIsAwaitingGeneratedInsight(false);
      setGenerationError(
        error instanceof Error
          ? error.message
          : "We're having trouble generating your insight. Please try again."
      );
    }
  }, [generateInsightMutation, reflection]);

  useEffect(() => {
    if (
      hasAutoGeneratedRef.current ||
      !autoGenerateInsight ||
      !reflection ||
      insight ||
      generateInsightMutation.isPending
    ) {
      return;
    }

    hasAutoGeneratedRef.current = true;
    void handleGenerateInsight();
  }, [
    autoGenerateInsight,
    reflection,
    insight,
    generateInsightMutation.isPending,
    handleGenerateInsight,
  ]);

  if (!reflectionId) {
    return (
      <PageContainer {...devComponentAttrs('ReflectionInsightPage')}>
        <p className="text-destructive">Missing reflection id.</p>
      </PageContainer>
    );
  }

  if (isLoading) {
    return <FullScreenLoader />;
  }

  const isGeneratingInsight =
    !insight && (generateInsightMutation.isPending || isAwaitingGeneratedInsight);

  return (
    <PageContainer>
      <div className="flex items-start justify-between gap-4">
        <PageHeader
          title="Another Perspective"
          description="A gentle read of this reflection, helping you notice patterns with more clarity and self-compassion."
        />

        {reflection ? (
          <ReflectionInsightActionsMenu
            reflectionId={reflection.id}
            onDeleted={() => {
              navigate('/reflections');
            }}
          />
        ) : null}
      </div>

      {reflectionError ? (
        <p className="text-destructive">
          We weren't able to load that reflection: {reflectionError.message}
        </p>
      ) : !reflection ? (
        <section className="rounded-lg border bg-card p-5 text-card-foreground shadow-sm">
          <h2 className="text-lg font-semibold">Reflection not found</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            This reflection may not exist or you may not have access to it.
          </p>
          <Button className="mt-4" asChild>
            <Link to="/reflections">Go to your reflections</Link>
          </Button>
        </section>
      ) : insightError ? (
        <p className="text-destructive">
          We weren't able to load that insight: {insightError.message}
        </p>
      ) : isGeneratingInsight ? (
        <section className="rounded-lg border bg-card p-5 text-card-foreground shadow-sm">
          <h2 className="text-lg font-semibold">Generating your insight...</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            We&apos;re taking a gentle look at your reflection.
          </p>
          <p className="mt-1 text-sm text-muted-foreground">This usually takes a few moments.</p>
        </section>
      ) : !insight ? (
        <section className="rounded-lg border bg-card p-5 text-card-foreground shadow-sm">
          <h2 className="text-lg font-semibold">Generate an insight</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            This reflection is saved. Generate an insight when you&apos;re ready.
          </p>
          <Button
            className="mt-4"
            onClick={handleGenerateInsight}
            disabled={generateInsightMutation.isPending}
          >
            {generateInsightMutation.isPending ? 'Generating...' : 'Generate Insight'}
          </Button>
          {generationError ? (
            <p className="mt-3 text-sm text-destructive">{generationError}</p>
          ) : null}
        </section>
      ) : (
        <InsightShell>
          <div className="pointer-events-none absolute inset-0" aria-hidden="true">
            <div className="insight-ambient absolute -top-20 left-1/2 h-56 w-56 -translate-x-1/2 rounded-full bg-primary/15 blur-3xl" />
            <div className="insight-ambient insight-ambient-delayed absolute bottom-0 right-0 h-48 w-48 rounded-full bg-primary/10 blur-3xl" />
          </div>

          <div className="relative space-y-6">
            <InsightIntro generatedAt={insight.created_at} />

            {reflection.insight_stale ? (
              <section
                className="insight-reveal rounded-xl border border-amber-500/40 bg-amber-500/10 p-5"
                style={{ animationDelay: '50ms' }}
              >
                <h3 className="text-base font-semibold text-amber-700">
                  This reflection has changed since your insight was generated.
                </h3>
                <p className="mt-2 text-sm text-amber-700/90">
                  Regenerate to align this insight with your latest reflection.
                </p>
                <Button
                  className="mt-4"
                  onClick={handleGenerateInsight}
                  disabled={generateInsightMutation.isPending}
                >
                  {generateInsightMutation.isPending ? 'Regenerating...' : 'Regenerate Insight'}
                </Button>
                {generationError ? (
                  <p className="mt-3 text-sm text-destructive">{generationError}</p>
                ) : null}
              </section>
            ) : null}

            <div className="insight-reveal" style={{ animationDelay: '80ms' }}>
              <InsightSection
                title="Summary"
                icon={<Sparkles className="h-4 w-4" />}
                className="rounded-xl border border-border/70 bg-background/35 p-5"
                contentClassName="mt-2 whitespace-pre-wrap text-base leading-8 text-foreground/95"
              >
                {insight.summary}
                <div className="mt-4 flex max-w-full flex-col items-start gap-1.5 rounded-xl border border-border/70 bg-background/70 px-4 py-3 text-sm text-foreground/90 sm:w-fit sm:flex-row sm:items-center sm:gap-2 sm:rounded-full sm:px-3 sm:py-1.5">
                  <span className="inline-flex items-center gap-1.5 text-xs font-medium uppercase tracking-[0.08em] text-muted-foreground">
                    <Heart className="h-3.5 w-3.5" />
                    Emotional tone
                  </span>
                  <span>{insight.emotional_tone}</span>
                </div>
              </InsightSection>
            </div>

            <div className="insight-reveal" style={{ animationDelay: '140ms' }}>
              <section className="rounded-xl border border-border/70 border-l-2 border-l-primary/45 bg-primary/8 p-5">
                <div className="flex items-center gap-1.5">
                  <SectionTitle icon={<Compass className="h-4 w-4" />}>
                    Another Side to Consider
                  </SectionTitle>
                  <InsightInfoPopover label="Learn more about another side to consider">
                    These are alternative ways of looking at your reflection. They are not meant to
                    replace your experience or tell you what is true, but to gently widen the lens.
                    Use them to ask: “What else might be possible here?” or “How would I view this
                    with more compassion or distance?”
                  </InsightInfoPopover>
                </div>
                {(insight.alternative_perspectives ?? []).length > 0 ? (
                  <InsightBulletList
                    items={insight.alternative_perspectives ?? []}
                    className="mt-3 space-y-2.5"
                    itemClassName="gap-2.5"
                  />
                ) : (
                  <p className="mt-3 text-sm text-muted-foreground">
                    No alternative perspectives available yet.
                  </p>
                )}
              </section>
            </div>

            <div
              className="insight-reveal grid gap-6 md:grid-cols-2"
              style={{ animationDelay: '200ms' }}
            >
              <section className="rounded-xl border border-border/70 bg-background/35 p-5">
                <div className="flex items-center gap-1.5">
                  <SectionTitle icon={<Layers3 className="h-4 w-4" />}>Main Themes</SectionTitle>
                  <InsightInfoPopover label="Learn more about main themes">
                    These are recurring ideas or topics Duality noticed in your reflection. They are
                    not labels or conclusions, but gentle signals about what may have been
                    emotionally or mentally present. Use them to ask: “Why did this stand out
                    today?” or “Has this theme appeared before?”
                  </InsightInfoPopover>
                </div>
                {(insight.themes ?? []).length > 0 && (
                  <InsightThemeList themes={insight.themes ?? []} />
                )}
              </section>

              <section className="rounded-xl border border-border/70 bg-background/35 p-5">
                <div className="flex items-center gap-1.5">
                  <SectionTitle icon={<Lightbulb className="h-4 w-4" />}>
                    Possible Assumptions
                  </SectionTitle>
                  <InsightInfoPopover label="Learn more about possible assumptions">
                    These are possible beliefs or interpretations that may be shaping how you see
                    the situation. They are not facts, and they may not all be true. Use them as
                    prompts to pause and ask: “What am I taking for granted here?” or “Is there
                    another way to see this?”
                  </InsightInfoPopover>
                </div>
                {(insight.assumptions ?? []).length > 0 ? (
                  <InsightBulletList
                    items={insight.assumptions ?? []}
                    className="mt-3 space-y-2.5"
                  />
                ) : (
                  <p className="mt-3 text-sm text-muted-foreground">No insights available yet.</p>
                )}
              </section>
            </div>

            <div className="insight-reveal" style={{ animationDelay: '260ms' }}>
              <SourceReflectionSection reflectionId={reflection.id} />
            </div>

            <div className="insight-reveal" style={{ animationDelay: '320ms' }}>
              <InsightSection
                title="A Question to Reflect On"
                icon={<CircleHelp className="h-4 w-4" />}
                className="rounded-xl border border-primary/30 bg-primary/10 p-6 text-center"
                contentClassName="mt-3 text-base leading-8"
              >
                {insight.reflection_question}
              </InsightSection>
            </div>
          </div>
        </InsightShell>
      )}
    </PageContainer>
  );
}
